version:  "3.4"
services:
  lamp-alpine:
    build:
      context: .
      args:
        Image_Created_var: "${Image_Created_Date}"
    container_name: "${CONTNAME}"
    image: "${ORG}/${IMGNAME}:${IMGTAG}"
    ports:
      - "127.0.0.1:80:80"
    networks:
      - private-network 

networks:
  private-network:
    driver: bridge