version:  '3'
services:
  lamp-alpine:
    build: .
    container_name: lamp
    ports:
      - "127.0.0.1:80:80"
    networks:
      - private-network   

networks:
  private-network:
    driver: bridge