version:  '3'
services:
  lamp-alpine:
    build: .
    networks:
      - internal
    container_name: 'lamp'
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8080:80"

networks:
  internal:
    driver: bridge