version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              python \
              python-dev \
              py-pip \
              curl
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build and run application Docker image
          command: |
            docker-compose up -d 
      - run:
          name: "Check Service is running or not"
          command: |
            chmod +x master-test.sh
            chmod +x development-test.sh
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo executing master test file
                ./master-test.sh
            fi
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
                echo executing development test file
                ./development-test.sh
            fi
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application as Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
              docker tag app $DOCKER_HUB_USER_ID/lamp-alpine:${CIRCLE_SHA1}
              docker tag app $DOCKER_HUB_USER_ID/lamp-alpine:latest
              docker push $DOCKER_HUB_USER_ID/lamp-alpine:${CIRCLE_SHA1}
              docker push $DOCKER_HUB_USER_ID/lamp-alpine:latest
            fi
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
              docker tag app $DOCKER_HUB_USER_ID/lamp-alpine:${CIRCLE_SHA1}
              docker tag app $DOCKER_HUB_USER_ID/lamp-alpine:development
              docker push $DOCKER_HUB_USER_ID/lamp-alpine:${CIRCLE_SHA1}
              docker push $DOCKER_HUB_USER_ID/lamp-alpine:development
            fi
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build